/**
 * SUBMODULE REGISTRY
 *
 * Centralna definicja wszystkich podmodułów w systemie DockPulse.
 * Każdy moduł może mieć wiele podmodułów, które można włączać/wyłączać per tenant.
 */

export enum ModuleCode {
  CRM = 'CRM',
  ORDERS = 'ORDERS',
  PRODUCTS = 'PRODUCTS',
  QUOTES = 'QUOTES',
  WMS = 'WMS',
  INVOICES = 'INVOICES',
  PROJECTS = 'PROJECTS',
  CALENDAR = 'CALENDAR',
  REPORTS = 'REPORTS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  INTEGRATIONS = 'INTEGRATIONS',
  HR = 'HR',
  BRANCHES = 'BRANCHES',
  SUPPLIERS = 'SUPPLIERS',
}

export interface SubmoduleDefinition {
  code: string;                    // np. "ORDERS.MEASUREMENTS"
  parentModule: ModuleCode;        // np. ModuleCode.ORDERS
  name: string;                    // "Measurements"
  namePl: string;                  // "Pomiary"
  description: string;
  descriptionPl: string;
  icon: string;                    // Lucide icon name

  category: 'INCLUDED' | 'ADDON';  // W cenie modułu czy dopłata
  price: number | null;            // Cena miesięczna (null = w cenie)

  isActive: boolean;               // Czy dostępny w systemie
  isBeta: boolean;                 // Czy w wersji beta

  features: string[];              // Lista funkcji
  routes: string[];                // Frontend routes
  apiEndpoints: string[];          // Backend endpoints

  requiredSubmodules: string[];    // Zależności od innych podmodułów
  conflictsWith: string[];         // Wykluczające się podmoduły

  defaultEnabled: boolean;         // Czy włączony domyślnie z modułem
  sortOrder: number;               // Kolejność wyświetlania
}

/**
 * Template branżowy - predefiniowane zestawy modułów i podmodułów
 */
export interface IndustryTemplate {
  code: 'SERVICES' | 'PRODUCTION' | 'TRADE';
  name: string;
  namePl: string;
  description: string;
  descriptionPl: string;
  icon: string;

  // Które moduły są CORE (wymagane)
  coreModules: ModuleCode[];

  // Które moduły są ADDON (opcjonalne)
  addonModules: ModuleCode[];

  // Które podmoduły są domyślnie włączone
  defaultSubmodules: string[];

  // Które podmoduły są ukryte (nie potrzebne dla tej branży)
  hiddenSubmodules: string[];
}

// ===========================================
// DEFINICJE PODMODUŁÓW - CRM
// ===========================================

export const CRM_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'CRM.CONTACTS',
    parentModule: ModuleCode.CRM,
    name: 'Basic Contacts',
    namePl: 'Podstawowe kontakty',
    description: 'Basic customer contact management',
    descriptionPl: 'Podstawowe zarządzanie kontaktami klientów',
    icon: 'Users',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Lista kontaktów',
      'Dodawanie/edycja/usuwanie',
      'Podstawowe dane (imię, email, telefon)',
      'Wyszukiwanie',
    ],
    routes: ['/customers', '/customers/:id'],
    apiEndpoints: ['/customers/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'CRM.TAGS',
    parentModule: ModuleCode.CRM,
    name: 'Tags & Categories',
    namePl: 'Tagi i kategorie',
    description: 'Customer segmentation with tags',
    descriptionPl: 'Segmentacja klientów za pomocą tagów',
    icon: 'Tag',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Niestandardowe tagi',
      'Kategorie klientów',
      'Filtrowanie po tagach',
      'Grupowanie',
    ],
    routes: [],
    apiEndpoints: ['/customers/:id/tags'],
    requiredSubmodules: ['CRM.CONTACTS'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    code: 'CRM.NOTES',
    parentModule: ModuleCode.CRM,
    name: 'Notes & History',
    namePl: 'Notatki i historia',
    description: 'Customer notes and interaction history',
    descriptionPl: 'Notatki i historia interakcji z klientem',
    icon: 'FileText',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Notatki do klienta',
      'Historia kontaktów',
      'Timeline wydarzeń',
      'Załączniki',
    ],
    routes: [],
    apiEndpoints: ['/customers/:id/notes'],
    requiredSubmodules: ['CRM.CONTACTS'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 3,
  },
  {
    code: 'CRM.HISTORY',
    parentModule: ModuleCode.CRM,
    name: 'Interaction History',
    namePl: 'Historia interakcji',
    description: 'Complete timeline of customer interactions',
    descriptionPl: 'Pełna historia interakcji z klientem',
    icon: 'History',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Timeline interakcji',
      'Telefony i spotkania',
      'Automatyczne wpisy (zamówienia, wyceny)',
      'Ręczne notatki',
    ],
    routes: ['/customers/:id/history'],
    apiEndpoints: ['/customers/:id/interactions/*'],
    requiredSubmodules: ['CRM.CONTACTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 4,
  },
  {
    code: 'CRM.IMPORT',
    parentModule: ModuleCode.CRM,
    name: 'Import',
    namePl: 'Import',
    description: 'Bulk import customers from CSV/Excel',
    descriptionPl: 'Masowy import klientów z CSV/Excel',
    icon: 'Upload',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Import z CSV/Excel',
      'Mapowanie kolumn',
      'Wykrywanie duplikatów',
      'Raport importu',
    ],
    routes: ['/customers/import'],
    apiEndpoints: ['/customers/import/*'],
    requiredSubmodules: ['CRM.CONTACTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 5,
  },
  {
    code: 'CRM.EXPORT',
    parentModule: ModuleCode.CRM,
    name: 'Export',
    namePl: 'Eksport',
    description: 'Export customers to CSV/Excel',
    descriptionPl: 'Eksport klientów do CSV/Excel',
    icon: 'Download',
    category: 'ADDON',
    price: 29,
    isActive: true,
    isBeta: false,
    features: [
      'Export do CSV/Excel',
      'Wybór pól do eksportu',
      'Filtrowanie danych',
      'Eksport segmentów',
    ],
    routes: ['/customers/export'],
    apiEndpoints: ['/customers/export'],
    requiredSubmodules: ['CRM.CONTACTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 6,
  },
  {
    code: 'CRM.DUPLICATES',
    parentModule: ModuleCode.CRM,
    name: 'Duplicate Detection',
    namePl: 'Wykrywanie duplikatów',
    description: 'Automatic duplicate customer detection',
    descriptionPl: 'Automatyczne wykrywanie duplikatów klientów',
    icon: 'Copy',
    category: 'ADDON',
    price: 39,
    isActive: true,
    isBeta: false,
    features: [
      'Detekcja po NIP',
      'Detekcja po nazwie',
      'Fuzzy matching',
      'Łączenie duplikatów',
    ],
    routes: ['/customers/duplicates'],
    apiEndpoints: ['/customers/duplicates/*'],
    requiredSubmodules: ['CRM.CONTACTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 7,
  },
  {
    code: 'CRM.SEGMENTS',
    parentModule: ModuleCode.CRM,
    name: 'Advanced Segmentation',
    namePl: 'Zaawansowana segmentacja',
    description: 'Advanced customer segmentation and filtering',
    descriptionPl: 'Zaawansowana segmentacja i filtrowanie klientów',
    icon: 'Filter',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Zaawansowane filtry',
      'Segmenty dynamiczne',
      'Zapisane widoki',
      'Analityka segmentów',
    ],
    routes: ['/customers/segments'],
    apiEndpoints: ['/customers/segments/*'],
    requiredSubmodules: ['CRM.CONTACTS', 'CRM.TAGS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 8,
  },
  {
    code: 'CRM.PORTAL',
    parentModule: ModuleCode.CRM,
    name: 'Customer Portal',
    namePl: 'Portal klienta',
    description: 'Self-service customer portal',
    descriptionPl: 'Portal samoobsługowy dla klientów',
    icon: 'Globe',
    category: 'ADDON',
    price: 149,
    isActive: true,
    isBeta: true,
    features: [
      'Logowanie dla klientów',
      'Podgląd zamówień',
      'Składanie zamówień online',
      'Historia współpracy',
    ],
    routes: ['/portal/*'],
    apiEndpoints: ['/portal/*'],
    requiredSubmodules: ['CRM.CONTACTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 10,
  },
];

// ===========================================
// DEFINICJE PODMODUŁÓW - ORDERS
// ===========================================

export const ORDERS_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'ORDERS.ITEMS',
    parentModule: ModuleCode.ORDERS,
    name: 'Order Items',
    namePl: 'Pozycje zamówienia',
    description: 'Full order line items management',
    descriptionPl: 'Pełne zarządzanie pozycjami zamówienia',
    icon: 'List',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Pozycje zamówienia',
      'Ilość i cena',
      'Obliczenia automatyczne',
      'VAT i rabaty',
    ],
    routes: [],
    apiEndpoints: ['/orders/:id/items'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'ORDERS.WORKFLOW',
    parentModule: ModuleCode.ORDERS,
    name: 'Basic Workflow',
    namePl: 'Podstawowy workflow',
    description: 'Basic order status management',
    descriptionPl: 'Podstawowe zarządzanie statusami zamówień',
    icon: 'GitBranch',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Statusy: new, in_progress, ready, completed',
      'Zmiana statusu',
      'Historia zmian',
    ],
    routes: [],
    apiEndpoints: ['/orders/:id/status'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    code: 'ORDERS.WORKFLOW_ADV',
    parentModule: ModuleCode.ORDERS,
    name: 'Advanced Workflow',
    namePl: 'Zaawansowany workflow',
    description: 'Custom statuses and workflow automation',
    descriptionPl: 'Własne statusy i automatyzacja workflow',
    icon: 'Workflow',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Niestandardowe statusy',
      'Workflow builder',
      'Automatyczne przejścia',
      'Powiadomienia o statusie',
    ],
    routes: ['/settings/workflow'],
    apiEndpoints: ['/workflow/*'],
    requiredSubmodules: ['ORDERS.WORKFLOW'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 3,
  },
  {
    code: 'ORDERS.MEASUREMENTS',
    parentModule: ModuleCode.ORDERS,
    name: 'Measurements',
    namePl: 'Pomiary',
    description: 'Measurement sheets and scheduling',
    descriptionPl: 'Arkusze pomiarowe i planowanie wizyt',
    icon: 'Ruler',
    category: 'ADDON',
    price: 99,
    isActive: true,
    isBeta: false,
    features: [
      'Arkusze pomiarowe',
      'Pozycje z wymiarami',
      'Zdjęcia z pomiaru',
      'Planowanie terminu',
      'Przypisanie technika',
    ],
    routes: ['/orders/:id/measurements'],
    apiEndpoints: ['/orders/:id/measurements/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 4,
  },
  {
    code: 'ORDERS.INSTALLATION',
    parentModule: ModuleCode.ORDERS,
    name: 'Installation',
    namePl: 'Montaż',
    description: 'Installation protocols and scheduling',
    descriptionPl: 'Protokoły montażu i planowanie wizyt',
    icon: 'Wrench',
    category: 'ADDON',
    price: 149,
    isActive: true,
    isBeta: false,
    features: [
      'Protokoły montażu',
      'Zdjęcia przed/po',
      'Planowanie terminu montażu',
      'Przypisanie ekipy',
      'Podpis klienta',
    ],
    routes: ['/orders/:id/installation'],
    apiEndpoints: ['/orders/:id/installation/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 5,
  },
  {
    code: 'ORDERS.ATTACHMENTS',
    parentModule: ModuleCode.ORDERS,
    name: 'Attachments',
    namePl: 'Załączniki',
    description: 'File attachments to orders',
    descriptionPl: 'Załączniki do zamówień',
    icon: 'Paperclip',
    category: 'ADDON',
    price: 29,
    isActive: true,
    isBeta: false,
    features: [
      'Upload plików',
      'Dokumenty PDF',
      'Word, Excel',
      'Lista załączników',
    ],
    routes: [],
    apiEndpoints: ['/orders/:id/attachments'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 6,
  },
  {
    code: 'ORDERS.PHOTOS',
    parentModule: ModuleCode.ORDERS,
    name: 'Photo Gallery',
    namePl: 'Galeria zdjęć',
    description: 'Photo gallery for orders',
    descriptionPl: 'Galeria zdjęć do zamówień',
    icon: 'Camera',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Upload zdjęć',
      'Galeria lightbox',
      'Zdjęcia przed/po',
      'Miniaturki',
    ],
    routes: ['/orders/:id/photos'],
    apiEndpoints: ['/orders/:id/photos/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 7,
  },
  {
    code: 'ORDERS.HISTORY',
    parentModule: ModuleCode.ORDERS,
    name: 'History & Audit',
    namePl: 'Historia zmian',
    description: 'Complete audit trail for orders',
    descriptionPl: 'Pełna historia zmian zamówień',
    icon: 'History',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Timeline zmian',
      'Kto i kiedy edytował',
      'Poprzednie wartości',
      'Historia statusów',
    ],
    routes: ['/orders/:id/history'],
    apiEndpoints: ['/orders/:id/audit/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 8,
  },
  {
    code: 'ORDERS.RECURRING',
    parentModule: ModuleCode.ORDERS,
    name: 'Recurring Orders',
    namePl: 'Zamówienia cykliczne',
    description: 'Automatic recurring orders',
    descriptionPl: 'Automatyczne zamówienia cykliczne',
    icon: 'Repeat',
    category: 'ADDON',
    price: 99,
    isActive: true,
    isBeta: true,
    features: [
      'Automatyczne powtarzanie',
      'Ustawienie cyklu (dzień/tydzień/miesiąc)',
      'Zarządzanie subskrypcjami',
    ],
    routes: ['/orders/recurring'],
    apiEndpoints: ['/orders/recurring/*'],
    requiredSubmodules: ['ORDERS.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 9,
  },
  {
    code: 'ORDERS.TEMPLATES',
    parentModule: ModuleCode.ORDERS,
    name: 'Order Templates',
    namePl: 'Szablony zamówień',
    description: 'Predefined order templates',
    descriptionPl: 'Predefiniowane szablony zamówień',
    icon: 'FileText',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Szablony zamówień',
      'Szybkie tworzenie',
      'Predefiniowane pozycje',
      'Zarządzanie szablonami',
    ],
    routes: ['/settings/order-templates'],
    apiEndpoints: ['/orders/templates/*'],
    requiredSubmodules: ['ORDERS.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 10,
  },
];

// ===========================================
// DEFINICJE PODMODUŁÓW - PRODUCTS
// ===========================================

export const PRODUCTS_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'PRODUCTS.CATALOG',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Product Catalog',
    namePl: 'Katalog produktów',
    description: 'Basic product catalog management',
    descriptionPl: 'Podstawowe zarządzanie katalogiem produktów',
    icon: 'Package',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Lista produktów',
      'SKU, nazwa, opis',
      'Cena bazowa',
      'Jednostka miary',
    ],
    routes: ['/products', '/products/:id'],
    apiEndpoints: ['/products/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'PRODUCTS.CATEGORIES',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Categories',
    namePl: 'Kategorie',
    description: 'Product categories and hierarchy',
    descriptionPl: 'Kategorie produktów i hierarchia',
    icon: 'FolderTree',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Kategorie główne',
      'Podkategorie',
      'Hierarchia',
      'Filtrowanie',
    ],
    routes: [],
    apiEndpoints: ['/products/categories/*'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    code: 'PRODUCTS.PRICELISTS',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Price Lists',
    namePl: 'Cenniki',
    description: 'Multiple price lists (wholesale, retail, etc)',
    descriptionPl: 'Wiele cenników (hurt, detal, itp.)',
    icon: 'DollarSign',
    category: 'ADDON',
    price: 69,
    isActive: true,
    isBeta: false,
    features: [
      'Wiele cenników',
      'Ceny hurtowe/detaliczne',
      'Rabaty grupowe',
      'Przypisanie do klienta',
    ],
    routes: ['/products/pricelists'],
    apiEndpoints: ['/products/pricelists/*'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 3,
  },
  {
    code: 'PRODUCTS.DIMENSIONS',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Dimensions',
    namePl: 'Wymiary',
    description: 'Product dimensions and weight',
    descriptionPl: 'Wymiary i waga produktów',
    icon: 'Maximize',
    category: 'ADDON',
    price: 39,
    isActive: true,
    isBeta: false,
    features: [
      'Długość, szerokość, wysokość',
      'Waga',
      'Obliczanie objętości',
      'Kalkulacja transportu',
    ],
    routes: [],
    apiEndpoints: ['/products/:id/dimensions'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 4,
  },
  {
    code: 'PRODUCTS.SURCHARGES',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Surcharges',
    namePl: 'Dopłaty',
    description: 'Product surcharges and modifications',
    descriptionPl: 'Dopłaty i modyfikacje produktów',
    icon: 'Plus',
    category: 'ADDON',
    price: 59,
    isActive: true,
    isBeta: false,
    features: [
      'Dopłaty do produktu',
      'Modyfikacje (kolor, rozmiar)',
      'Obliczanie dopłat',
      'Warianty produktów',
    ],
    routes: [],
    apiEndpoints: ['/products/:id/surcharges'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 5,
  },
  {
    code: 'PRODUCTS.IMPORT',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Import/Export',
    namePl: 'Import/Export',
    description: 'Bulk product import and export',
    descriptionPl: 'Masowy import i eksport produktów',
    icon: 'Download',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Import z CSV/Excel',
      'Export do CSV/Excel',
      'Aktualizacja cen',
      'Walidacja danych',
    ],
    routes: ['/products/import'],
    apiEndpoints: ['/products/import', '/products/export'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 6,
  },
  {
    code: 'PRODUCTS.BARCODES',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Barcodes',
    namePl: 'Kody kreskowe',
    description: 'Barcode generation and scanning',
    descriptionPl: 'Generowanie i skanowanie kodów kreskowych',
    icon: 'Scan',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Generowanie kodów EAN',
      'Skanowanie',
      'Etykiety',
      'Integracja z magazynem',
    ],
    routes: ['/products/barcodes'],
    apiEndpoints: ['/products/:id/barcode'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 7,
  },
  {
    code: 'PRODUCTS.VARIANTS',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Product Variants',
    namePl: 'Warianty produktów',
    description: 'Product variants (sizes, colors, etc)',
    descriptionPl: 'Warianty produktów (rozmiary, kolory, itp.)',
    icon: 'Grid',
    category: 'ADDON',
    price: 89,
    isActive: true,
    isBeta: false,
    features: [
      'Warianty produktów',
      'Rozmiary, kolory',
      'Osobne SKU',
      'Zarządzanie stanami per wariant',
    ],
    routes: ['/products/:id/variants'],
    apiEndpoints: ['/products/:id/variants/*'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 8,
  },
  {
    code: 'PRODUCTS.IMAGES',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Product Images',
    namePl: 'Zdjęcia produktów',
    description: 'Product image gallery',
    descriptionPl: 'Galeria zdjęć produktów',
    icon: 'Image',
    category: 'ADDON',
    price: 39,
    isActive: true,
    isBeta: false,
    features: [
      'Wiele zdjęć na produkt',
      'Zdjęcie główne',
      'Galeria',
      'Optymalizacja obrazów',
    ],
    routes: [],
    apiEndpoints: ['/products/:id/images/*'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 9,
  },
  {
    code: 'PRODUCTS.ATTRIBUTES',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Custom Attributes',
    namePl: 'Atrybuty własne',
    description: 'Custom product attributes and specifications',
    descriptionPl: 'Własne atrybuty i specyfikacje produktów',
    icon: 'ListChecks',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Dowolne atrybuty',
      'Specyfikacje techniczne',
      'Filtrowanie po atrybutach',
      'Grupowanie atrybutów',
    ],
    routes: ['/products/attributes'],
    apiEndpoints: ['/products/attributes/*'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 10,
  },
  {
    code: 'PRODUCTS.BUNDLES',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Product Bundles',
    namePl: 'Zestawy produktów',
    description: 'Product bundles and kits',
    descriptionPl: 'Zestawy i kity produktów',
    icon: 'Package2',
    category: 'ADDON',
    price: 69,
    isActive: true,
    isBeta: false,
    features: [
      'Tworzenie zestawów',
      'Składowe zestawu',
      'Cena zestawu',
      'Zarządzanie stanem zestawu',
    ],
    routes: ['/products/bundles'],
    apiEndpoints: ['/products/bundles/*'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 11,
  },
  {
    code: 'PRODUCTS.SUPPLIERS',
    parentModule: ModuleCode.PRODUCTS,
    name: 'Suppliers',
    namePl: 'Dostawcy',
    description: 'Product suppliers management',
    descriptionPl: 'Zarządzanie dostawcami produktów',
    icon: 'Truck',
    category: 'ADDON',
    price: 59,
    isActive: true,
    isBeta: false,
    features: [
      'Lista dostawców',
      'Przypisanie dostawcy do produktu',
      'Ceny zakupu',
      'Czas dostawy',
    ],
    routes: ['/products/suppliers'],
    apiEndpoints: ['/products/suppliers/*'],
    requiredSubmodules: ['PRODUCTS.CATALOG'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 12,
  },
];

// ===========================================
// DEFINICJE PODMODUŁÓW - QUOTES
// ===========================================

export const QUOTES_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'QUOTES.ITEMS',
    parentModule: ModuleCode.QUOTES,
    name: 'Quote Items',
    namePl: 'Pozycje oferty',
    description: 'Quote line items management',
    descriptionPl: 'Zarządzanie pozycjami oferty',
    icon: 'List',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Pozycje oferty',
      'Ilość i cena',
      'Obliczenia',
      'Rabaty',
    ],
    routes: [],
    apiEndpoints: ['/quotes/:id/items'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'QUOTES.PDF',
    parentModule: ModuleCode.QUOTES,
    name: 'PDF Generation',
    namePl: 'Generowanie PDF',
    description: 'Professional PDF quote generation',
    descriptionPl: 'Profesjonalne generowanie ofert PDF',
    icon: 'FileText',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Szablony PDF',
      'Logo firmy',
      'Własny layout',
      'Download PDF',
    ],
    routes: [],
    apiEndpoints: ['/quotes/:id/pdf'],
    requiredSubmodules: ['QUOTES.ITEMS'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    code: 'QUOTES.EMAIL',
    parentModule: ModuleCode.QUOTES,
    name: 'Email Sending',
    namePl: 'Wysyłka email',
    description: 'Send quotes via email',
    descriptionPl: 'Wysyłanie ofert przez email',
    icon: 'Mail',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Wysyłka na email',
      'Szablon wiadomości',
      'Załącznik PDF',
      'Historia wysyłek',
    ],
    routes: [],
    apiEndpoints: ['/quotes/:id/send'],
    requiredSubmodules: ['QUOTES.PDF'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 3,
  },
  {
    code: 'QUOTES.CALCULATOR',
    parentModule: ModuleCode.QUOTES,
    name: 'Price Calculator',
    namePl: 'Kalkulator cen',
    description: 'Advanced price calculation with formulas',
    descriptionPl: 'Zaawansowany kalkulator cen z formułami',
    icon: 'Calculator',
    category: 'ADDON',
    price: 89,
    isActive: true,
    isBeta: false,
    features: [
      'Formuły cenowe',
      'Przeliczanie wymiarów',
      'Dopłaty automatyczne',
      'Zniżki hurtowe',
    ],
    routes: [],
    apiEndpoints: ['/quotes/:id/calculate'],
    requiredSubmodules: ['QUOTES.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 4,
  },
  {
    code: 'QUOTES.APPROVAL',
    parentModule: ModuleCode.QUOTES,
    name: 'Approval Workflow',
    namePl: 'Workflow akceptacji',
    description: 'Multi-level quote approval process',
    descriptionPl: 'Wielopoziomowa akceptacja ofert',
    icon: 'CheckCircle',
    category: 'ADDON',
    price: 99,
    isActive: true,
    isBeta: true,
    features: [
      'Akceptacja przez managera',
      'Wiele poziomów',
      'Powiadomienia',
      'Historia akceptacji',
    ],
    routes: ['/quotes/approvals'],
    apiEndpoints: ['/quotes/:id/approve'],
    requiredSubmodules: ['QUOTES.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 5,
  },
  {
    code: 'QUOTES.VERSIONS',
    parentModule: ModuleCode.QUOTES,
    name: 'Version History',
    namePl: 'Historia wersji',
    description: 'Quote version tracking and comparison',
    descriptionPl: 'Śledzenie wersji i porównywanie ofert',
    icon: 'GitCompare',
    category: 'ADDON',
    price: 59,
    isActive: true,
    isBeta: false,
    features: [
      'Wersjonowanie ofert',
      'Porównywanie wersji',
      'Historia zmian',
      'Przywracanie wersji',
    ],
    routes: ['/quotes/:id/versions'],
    apiEndpoints: ['/quotes/:id/versions/*'],
    requiredSubmodules: ['QUOTES.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 6,
  },
  {
    code: 'QUOTES.TEMPLATES',
    parentModule: ModuleCode.QUOTES,
    name: 'Quote Templates',
    namePl: 'Szablony ofert',
    description: 'Predefined quote templates',
    descriptionPl: 'Predefiniowane szablony ofert',
    icon: 'FileStack',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Szablony ofert',
      'Predefiniowane pozycje',
      'Szybkie tworzenie',
      'Zarządzanie szablonami',
    ],
    routes: ['/settings/quote-templates'],
    apiEndpoints: ['/quotes/templates/*'],
    requiredSubmodules: ['QUOTES.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 7,
  },
  {
    code: 'QUOTES.DISCOUNTS',
    parentModule: ModuleCode.QUOTES,
    name: 'Advanced Discounts',
    namePl: 'Zaawansowane rabaty',
    description: 'Complex discount rules and promotions',
    descriptionPl: 'Złożone reguły rabatowe i promocje',
    icon: 'BadgePercent',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Rabaty procentowe i kwotowe',
      'Rabaty wielopoziomowe',
      'Promocje czasowe',
      'Kupony rabatowe',
    ],
    routes: [],
    apiEndpoints: ['/quotes/:id/discounts'],
    requiredSubmodules: ['QUOTES.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 8,
  },
  {
    code: 'QUOTES.VALIDITY',
    parentModule: ModuleCode.QUOTES,
    name: 'Validity Management',
    namePl: 'Zarządzanie ważnością',
    description: 'Quote validity periods and expiration',
    descriptionPl: 'Okresy ważności i wygasanie ofert',
    icon: 'Clock',
    category: 'ADDON',
    price: 39,
    isActive: true,
    isBeta: false,
    features: [
      'Data ważności oferty',
      'Automatyczne wygaszanie',
      'Powiadomienia o wygaśnięciu',
      'Przedłużanie ważności',
    ],
    routes: [],
    apiEndpoints: ['/quotes/:id/validity'],
    requiredSubmodules: ['QUOTES.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 9,
  },
  {
    code: 'QUOTES.FOLLOW_UP',
    parentModule: ModuleCode.QUOTES,
    name: 'Follow-up Reminders',
    namePl: 'Przypomnienia follow-up',
    description: 'Automatic follow-up reminders',
    descriptionPl: 'Automatyczne przypomnienia o kontakcie',
    icon: 'Bell',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Harmonogram kontaktu',
      'Automatyczne przypomnienia',
      'Email follow-up',
      'Notatki z rozmów',
    ],
    routes: ['/quotes/:id/follow-up'],
    apiEndpoints: ['/quotes/:id/follow-up/*'],
    requiredSubmodules: ['QUOTES.ITEMS', 'QUOTES.EMAIL'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 10,
  },
  {
    code: 'QUOTES.ANALYTICS',
    parentModule: ModuleCode.QUOTES,
    name: 'Quote Analytics',
    namePl: 'Analityka ofert',
    description: 'Quote performance analytics',
    descriptionPl: 'Analityka skuteczności ofert',
    icon: 'LineChart',
    category: 'ADDON',
    price: 89,
    isActive: true,
    isBeta: false,
    features: [
      'Wskaźnik konwersji',
      'Średnia wartość oferty',
      'Czas do decyzji',
      'Raporty ofert',
    ],
    routes: ['/quotes/analytics'],
    apiEndpoints: ['/quotes/analytics/*'],
    requiredSubmodules: ['QUOTES.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 11,
  },
  {
    code: 'QUOTES.COMPARISON',
    parentModule: ModuleCode.QUOTES,
    name: 'Quote Comparison',
    namePl: 'Porównywanie ofert',
    description: 'Side-by-side quote comparison',
    descriptionPl: 'Porównywanie ofert obok siebie',
    icon: 'ArrowLeftRight',
    category: 'ADDON',
    price: 59,
    isActive: true,
    isBeta: false,
    features: [
      'Porównywanie wielu ofert',
      'Tabela porównawcza',
      'Export porównania',
      'Prezentacja dla klienta',
    ],
    routes: ['/quotes/compare'],
    apiEndpoints: ['/quotes/compare'],
    requiredSubmodules: ['QUOTES.ITEMS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 12,
  },
];

// ===========================================
// DEFINICJE PODMODUŁÓW - WMS
// ===========================================

export const WMS_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'WMS.WAREHOUSES',
    parentModule: ModuleCode.WMS,
    name: 'Warehouses',
    namePl: 'Magazyny',
    description: 'Multiple warehouse management',
    descriptionPl: 'Zarządzanie wieloma magazynami',
    icon: 'Warehouse',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Wiele magazynów',
      'Lokalizacje',
      'Transfery między magazynami',
    ],
    routes: ['/wms/warehouses'],
    apiEndpoints: ['/wms/warehouses/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'WMS.LOCATIONS',
    parentModule: ModuleCode.WMS,
    name: 'Locations',
    namePl: 'Lokalizacje',
    description: 'Warehouse zones and locations',
    descriptionPl: 'Strefy i lokalizacje w magazynie',
    icon: 'MapPin',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Strefy magazynowe',
      'Regały i półki',
      'Mapowanie lokalizacji',
    ],
    routes: [],
    apiEndpoints: ['/wms/locations/*'],
    requiredSubmodules: ['WMS.WAREHOUSES'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    code: 'WMS.STOCK',
    parentModule: ModuleCode.WMS,
    name: 'Stock Management',
    namePl: 'Stany magazynowe',
    description: 'Real-time stock levels',
    descriptionPl: 'Stany magazynowe w czasie rzeczywistym',
    icon: 'Package',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Aktualny stan',
      'Rezerwacje',
      'Dostępność',
      'Alerty niskiego stanu',
    ],
    routes: ['/wms/stock'],
    apiEndpoints: ['/wms/stock/*'],
    requiredSubmodules: ['WMS.WAREHOUSES'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 3,
  },
  {
    code: 'WMS.DOCUMENTS',
    parentModule: ModuleCode.WMS,
    name: 'Warehouse Documents',
    namePl: 'Dokumenty magazynowe',
    description: 'PZ, WZ, MM documents',
    descriptionPl: 'Dokumenty PZ, WZ, MM',
    icon: 'FileText',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Przyjęcia (PZ)',
      'Wydania (WZ)',
      'Przesunięcia (MM)',
      'Historia dokumentów',
    ],
    routes: ['/wms/documents'],
    apiEndpoints: ['/wms/documents/*'],
    requiredSubmodules: ['WMS.STOCK'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 4,
  },
  {
    code: 'WMS.INVENTORY',
    parentModule: ModuleCode.WMS,
    name: 'Inventory',
    namePl: 'Inwentaryzacja',
    description: 'Stock taking and inventory management',
    descriptionPl: 'Inwentaryzacja i liczenie stanów',
    icon: 'ClipboardCheck',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Inwentaryzacja',
      'Liczenie stanów',
      'Korekty',
      'Raporty różnic',
    ],
    routes: ['/wms/inventory'],
    apiEndpoints: ['/wms/inventory/*'],
    requiredSubmodules: ['WMS.STOCK'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 5,
  },
  {
    code: 'WMS.CONTAINERS',
    parentModule: ModuleCode.WMS,
    name: 'Containers',
    namePl: 'Kontenery',
    description: 'Container and pallet management',
    descriptionPl: 'Zarządzanie kontenerami i paletami',
    icon: 'Box',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Kontenery',
      'Palety',
      'Śledzenie opakowań',
    ],
    routes: [],
    apiEndpoints: ['/wms/containers/*'],
    requiredSubmodules: ['WMS.WAREHOUSES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 6,
  },
  {
    code: 'WMS.BARCODES',
    parentModule: ModuleCode.WMS,
    name: 'Barcode Scanning',
    namePl: 'Skanowanie kodów',
    description: 'Barcode scanning for warehouse operations',
    descriptionPl: 'Skanowanie kodów kreskowych w magazynie',
    icon: 'Scan',
    category: 'ADDON',
    price: 99,
    isActive: true,
    isBeta: false,
    features: [
      'Skanowanie przy przyjęciu',
      'Skanowanie przy wydaniu',
      'Picking list',
      'Etykiety',
    ],
    routes: [],
    apiEndpoints: ['/wms/scan/*'],
    requiredSubmodules: ['WMS.DOCUMENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 7,
  },
  {
    code: 'WMS.BATCHES',
    parentModule: ModuleCode.WMS,
    name: 'Batch Tracking',
    namePl: 'Śledzenie partii',
    description: 'Batch and lot number tracking',
    descriptionPl: 'Śledzenie partii i numerów LOT',
    icon: 'Hash',
    category: 'ADDON',
    price: 89,
    isActive: true,
    isBeta: true,
    features: [
      'Numery partii',
      'Numery LOT',
      'Terminy ważności',
      'Traceability',
    ],
    routes: [],
    apiEndpoints: ['/wms/batches/*'],
    requiredSubmodules: ['WMS.STOCK'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 8,
  },
  {
    code: 'WMS.ALERTS',
    parentModule: ModuleCode.WMS,
    name: 'Stock Alerts',
    namePl: 'Alerty magazynowe',
    description: 'Low stock and expiry alerts',
    descriptionPl: 'Alerty o niskim stanie i ważności',
    icon: 'AlertTriangle',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Alert niskiego stanu',
      'Alert ważności',
      'Powiadomienia email/SMS',
      'Progi alarmowe',
    ],
    routes: [],
    apiEndpoints: ['/wms/alerts/*'],
    requiredSubmodules: ['WMS.STOCK'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 9,
  },
  {
    code: 'WMS.LABELS',
    parentModule: ModuleCode.WMS,
    name: 'Label Printing',
    namePl: 'Drukowanie etykiet',
    description: 'Zebra and thermal printer support',
    descriptionPl: 'Obsługa drukarek Zebra i termicznych',
    icon: 'Printer',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Drukowanie etykiet',
      'Zebra ZPL',
      'Etykiety z kodami',
      'Szablony etykiet',
    ],
    routes: ['/wms/labels'],
    apiEndpoints: ['/wms/labels/*'],
    requiredSubmodules: ['WMS.STOCK'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 10,
  },
  {
    code: 'WMS.EXPIRY',
    parentModule: ModuleCode.WMS,
    name: 'Expiry Tracking',
    namePl: 'Daty ważności',
    description: 'FEFO (First Expire First Out) management',
    descriptionPl: 'Zarządzanie datami ważności (FEFO)',
    icon: 'Calendar',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Daty ważności',
      'FEFO (First Expire First Out)',
      'Alerty wygaśnięcia',
      'Raport przeterminowanych',
    ],
    routes: ['/wms/expiry'],
    apiEndpoints: ['/wms/expiry/*'],
    requiredSubmodules: ['WMS.STOCK', 'WMS.BATCHES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 11,
  },
];

// ===========================================
// DEFINICJE PODMODUŁÓW - CALENDAR
// ===========================================

export const CALENDAR_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'CALENDAR.EVENTS',
    parentModule: ModuleCode.CALENDAR,
    name: 'Events',
    namePl: 'Wydarzenia',
    description: 'Calendar events and scheduling',
    descriptionPl: 'Wydarzenia kalendarza i planowanie',
    icon: 'Calendar',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Dodawanie wydarzeń',
      'Terminy',
      'Przypomnienia',
      'Widok dzienny/tygodniowy/miesięczny',
    ],
    routes: ['/calendar'],
    apiEndpoints: ['/calendar/events/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'CALENDAR.GOOGLE',
    parentModule: ModuleCode.CALENDAR,
    name: 'Google Calendar Sync',
    namePl: 'Synchronizacja z Google',
    description: 'Two-way sync with Google Calendar',
    descriptionPl: 'Dwukierunkowa synchronizacja z Google Calendar',
    icon: 'Cloud',
    category: 'ADDON',
    price: 69,
    isActive: true,
    isBeta: false,
    features: [
      'Sync z Google Calendar',
      'Import wydarzeń',
      'Export do Google',
      'Dwukierunkowa synchronizacja',
    ],
    routes: [],
    apiEndpoints: ['/calendar/google/*'],
    requiredSubmodules: ['CALENDAR.EVENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 2,
  },
  {
    code: 'CALENDAR.BOOKING',
    parentModule: ModuleCode.CALENDAR,
    name: 'Online Booking',
    namePl: 'Rezerwacja online',
    description: 'Customer self-service booking',
    descriptionPl: 'Rezerwacja terminów przez klientów',
    icon: 'CalendarCheck',
    category: 'ADDON',
    price: 99,
    isActive: true,
    isBeta: true,
    features: [
      'Publiczny link do rezerwacji',
      'Dostępne terminy',
      'Automatyczne potwierdzenia',
      'Integracja z kalendarzem',
    ],
    routes: ['/booking/*'],
    apiEndpoints: ['/booking/*'],
    requiredSubmodules: ['CALENDAR.EVENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 3,
  },
  {
    code: 'CALENDAR.TASKS',
    parentModule: ModuleCode.CALENDAR,
    name: 'Tasks',
    namePl: 'Zadania',
    description: 'Task management with calendar',
    descriptionPl: 'Zarządzanie zadaniami z kalendarzem',
    icon: 'CheckSquare',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Lista zadań',
      'Terminy',
      'Priorytety',
      'Przypisanie do użytkowników',
    ],
    routes: ['/tasks'],
    apiEndpoints: ['/calendar/tasks/*'],
    requiredSubmodules: ['CALENDAR.EVENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 4,
  },
  {
    code: 'CALENDAR.RECURRING',
    parentModule: ModuleCode.CALENDAR,
    name: 'Recurring Events',
    namePl: 'Wydarzenia cykliczne',
    description: 'Recurring and repeating events',
    descriptionPl: 'Wydarzenia cykliczne i powtarzające się',
    icon: 'Repeat',
    category: 'ADDON',
    price: 39,
    isActive: true,
    isBeta: false,
    features: [
      'Wydarzenia cykliczne',
      'Wzorce powtarzania',
      'Edycja serii',
      'Wyjątki',
    ],
    routes: [],
    apiEndpoints: ['/calendar/recurring/*'],
    requiredSubmodules: ['CALENDAR.EVENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 5,
  },
  {
    code: 'CALENDAR.REMINDERS',
    parentModule: ModuleCode.CALENDAR,
    name: 'Advanced Reminders',
    namePl: 'Zaawansowane przypomnienia',
    description: 'Multi-channel reminder system',
    descriptionPl: 'System przypomnień wielokanałowych',
    icon: 'Bell',
    category: 'ADDON',
    price: 59,
    isActive: true,
    isBeta: false,
    features: [
      'Email reminders',
      'SMS reminders',
      'Push notifications',
      'Niestandardowe reguły',
    ],
    routes: [],
    apiEndpoints: ['/calendar/reminders/*'],
    requiredSubmodules: ['CALENDAR.EVENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 6,
  },
  {
    code: 'CALENDAR.TEAMS',
    parentModule: ModuleCode.CALENDAR,
    name: 'Team Calendars',
    namePl: 'Kalendarze zespołowe',
    description: 'Shared team calendars',
    descriptionPl: 'Współdzielone kalendarze zespołów',
    icon: 'Users',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Kalendarze zespołów',
      'Współdzielenie',
      'Uprawnienia',
      'Widok zasobów',
    ],
    routes: ['/calendar/teams'],
    apiEndpoints: ['/calendar/teams/*'],
    requiredSubmodules: ['CALENDAR.EVENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 7,
  },
  {
    code: 'CALENDAR.RESOURCES',
    parentModule: ModuleCode.CALENDAR,
    name: 'Resource Booking',
    namePl: 'Rezerwacja zasobów',
    description: 'Room and equipment booking',
    descriptionPl: 'Rezerwacja sal i sprzętu',
    icon: 'Building',
    category: 'ADDON',
    price: 89,
    isActive: true,
    isBeta: false,
    features: [
      'Rezerwacja sal',
      'Rezerwacja sprzętu',
      'Dostępność zasobów',
      'Konflikt rezerwacji',
    ],
    routes: ['/calendar/resources'],
    apiEndpoints: ['/calendar/resources/*'],
    requiredSubmodules: ['CALENDAR.EVENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 8,
  },
  {
    code: 'CALENDAR.OUTLOOK',
    parentModule: ModuleCode.CALENDAR,
    name: 'Outlook Sync',
    namePl: 'Synchronizacja z Outlook',
    description: 'Two-way sync with Microsoft Outlook',
    descriptionPl: 'Dwukierunkowa synchronizacja z Outlook',
    icon: 'Mail',
    category: 'ADDON',
    price: 69,
    isActive: true,
    isBeta: true,
    features: [
      'Sync z Outlook',
      'Import wydarzeń',
      'Export do Outlook',
      'Dwukierunkowa synchronizacja',
    ],
    routes: [],
    apiEndpoints: ['/calendar/outlook/*'],
    requiredSubmodules: ['CALENDAR.EVENTS'],
    conflictsWith: ['CALENDAR.GOOGLE'],
    defaultEnabled: false,
    sortOrder: 9,
  },
  {
    code: 'CALENDAR.AVAILABILITY',
    parentModule: ModuleCode.CALENDAR,
    name: 'Availability Management',
    namePl: 'Zarządzanie dostępnością',
    description: 'User availability and time slots',
    descriptionPl: 'Dostępność użytkowników i sloty czasowe',
    icon: 'Clock',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Godziny pracy',
      'Wolne sloty',
      'Blokowanie terminów',
      'Strefa czasowa',
    ],
    routes: ['/calendar/availability'],
    apiEndpoints: ['/calendar/availability/*'],
    requiredSubmodules: ['CALENDAR.EVENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 10,
  },
];

// ===========================================
// DEFINICJE PODMODUŁÓW - INVOICES
// ===========================================

export const INVOICES_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'INVOICES.SALES',
    parentModule: ModuleCode.INVOICES,
    name: 'Sales Invoices',
    namePl: 'Faktury sprzedaży',
    description: 'Create and manage sales invoices',
    descriptionPl: 'Tworzenie i zarządzanie fakturami sprzedaży',
    icon: 'FileText',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Faktury VAT',
      'Faktury proforma',
      'Automatyczna numeracja',
      'Pozycje faktury',
    ],
    routes: ['/invoices', '/invoices/:id'],
    apiEndpoints: ['/invoices/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'INVOICES.PDF',
    parentModule: ModuleCode.INVOICES,
    name: 'PDF Generation',
    namePl: 'Generowanie PDF',
    description: 'Professional invoice PDF generation',
    descriptionPl: 'Profesjonalne generowanie faktur PDF',
    icon: 'Download',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Szablony PDF',
      'Logo firmy',
      'Własny layout',
      'Download',
    ],
    routes: [],
    apiEndpoints: ['/invoices/:id/pdf'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    code: 'INVOICES.PAYMENTS',
    parentModule: ModuleCode.INVOICES,
    name: 'Payment Tracking',
    namePl: 'Śledzenie płatności',
    description: 'Track invoice payments and status',
    descriptionPl: 'Śledzenie płatności i statusu faktur',
    icon: 'DollarSign',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Status płatności',
      'Przypomnienia o płatności',
      'Historia wpłat',
      'Częściowe płatności',
    ],
    routes: [],
    apiEndpoints: ['/invoices/:id/payments'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 3,
  },
  {
    code: 'INVOICES.EMAIL',
    parentModule: ModuleCode.INVOICES,
    name: 'Email Sending',
    namePl: 'Wysyłka email',
    description: 'Send invoices via email',
    descriptionPl: 'Wysyłanie faktur przez email',
    icon: 'Mail',
    category: 'ADDON',
    price: 29,
    isActive: true,
    isBeta: false,
    features: [
      'Wysyłka na email',
      'Szablon wiadomości',
      'Załącznik PDF',
      'Historia wysyłek',
    ],
    routes: [],
    apiEndpoints: ['/invoices/:id/send'],
    requiredSubmodules: ['INVOICES.SALES', 'INVOICES.PDF'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 4,
  },
  {
    code: 'INVOICES.RECURRING',
    parentModule: ModuleCode.INVOICES,
    name: 'Recurring Invoices',
    namePl: 'Faktury cykliczne',
    description: 'Automatic recurring invoices',
    descriptionPl: 'Automatyczne faktury cykliczne',
    icon: 'Repeat',
    category: 'ADDON',
    price: 99,
    isActive: true,
    isBeta: false,
    features: [
      'Faktury cykliczne',
      'Automatyczne wystawianie',
      'Harmonogram',
      'Subskrypcje',
    ],
    routes: ['/invoices/recurring'],
    apiEndpoints: ['/invoices/recurring/*'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 5,
  },
  {
    code: 'INVOICES.CORRECTIONS',
    parentModule: ModuleCode.INVOICES,
    name: 'Corrections & Credit Notes',
    namePl: 'Korekty i faktury korygujące',
    description: 'Invoice corrections and credit notes',
    descriptionPl: 'Faktury korygujące i noty kredytowe',
    icon: 'FileEdit',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Faktury korygujące',
      'Noty kredytowe',
      'Powiązanie z oryginałem',
      'Historia korekt',
    ],
    routes: ['/invoices/:id/corrections'],
    apiEndpoints: ['/invoices/:id/corrections/*'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 6,
  },
  {
    code: 'INVOICES.TEMPLATES',
    parentModule: ModuleCode.INVOICES,
    name: 'Invoice Templates',
    namePl: 'Szablony faktur',
    description: 'Predefined invoice templates',
    descriptionPl: 'Predefiniowane szablony faktur',
    icon: 'FileStack',
    category: 'ADDON',
    price: 39,
    isActive: true,
    isBeta: false,
    features: [
      'Szablony faktur',
      'Predefiniowane pozycje',
      'Szybkie tworzenie',
      'Zarządzanie szablonami',
    ],
    routes: ['/settings/invoice-templates'],
    apiEndpoints: ['/invoices/templates/*'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 7,
  },
  {
    code: 'INVOICES.SERIES',
    parentModule: ModuleCode.INVOICES,
    name: 'Invoice Series',
    namePl: 'Serie faktur',
    description: 'Multiple invoice series and numbering',
    descriptionPl: 'Wiele serii faktur i numeracji',
    icon: 'Hash',
    category: 'ADDON',
    price: 59,
    isActive: true,
    isBeta: false,
    features: [
      'Wiele serii numeracji',
      'Serie per oddział',
      'Prefiksy i sufiksy',
      'Resetowanie numeracji',
    ],
    routes: ['/settings/invoice-series'],
    apiEndpoints: ['/invoices/series/*'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 8,
  },
  {
    code: 'INVOICES.VAT',
    parentModule: ModuleCode.INVOICES,
    name: 'VAT Reports',
    namePl: 'Raporty VAT',
    description: 'VAT reports and declarations',
    descriptionPl: 'Raporty VAT i deklaracje',
    icon: 'BarChart',
    category: 'ADDON',
    price: 89,
    isActive: true,
    isBeta: false,
    features: [
      'Rejestr VAT',
      'JPK_VAT',
      'Deklaracja VAT',
      'Analiza VAT',
    ],
    routes: ['/invoices/vat'],
    apiEndpoints: ['/invoices/vat/*'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 9,
  },
  {
    code: 'INVOICES.EXPORT',
    parentModule: ModuleCode.INVOICES,
    name: 'Accounting Export',
    namePl: 'Eksport do księgowości',
    description: 'Export to accounting software',
    descriptionPl: 'Eksport do programów księgowych',
    icon: 'Upload',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Export do programów księgowych',
      'Format XML/CSV',
      'Integracja z Symfonia, Insert',
      'Automatyczny eksport',
    ],
    routes: ['/invoices/export'],
    apiEndpoints: ['/invoices/export/*'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 10,
  },
  {
    code: 'INVOICES.ADVANCES',
    parentModule: ModuleCode.INVOICES,
    name: 'Advance Payments',
    namePl: 'Zaliczki',
    description: 'Advance payment invoices',
    descriptionPl: 'Faktury zaliczkowe',
    icon: 'CreditCard',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Faktury zaliczkowe',
      'Rozliczanie zaliczek',
      'Powiązanie z fakturą końcową',
      'Historia zaliczek',
    ],
    routes: [],
    apiEndpoints: ['/invoices/:id/advances/*'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 11,
  },
  {
    code: 'INVOICES.REMINDERS',
    parentModule: ModuleCode.INVOICES,
    name: 'Payment Reminders',
    namePl: 'Monity',
    description: 'Automatic payment reminders',
    descriptionPl: 'Automatyczne upomnienia o płatność',
    icon: 'BellRing',
    category: 'ADDON',
    price: 59,
    isActive: true,
    isBeta: false,
    features: [
      'Automatyczne upomnienia',
      'Wielostopniowe',
      'Email/SMS',
      'Historia monitów',
    ],
    routes: ['/invoices/:id/reminders'],
    apiEndpoints: ['/invoices/:id/reminders/*'],
    requiredSubmodules: ['INVOICES.SALES', 'INVOICES.PAYMENTS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 12,
  },
  {
    code: 'INVOICES.REPORTS',
    parentModule: ModuleCode.INVOICES,
    name: 'Invoice Reports',
    namePl: 'Raporty faktur',
    description: 'Comprehensive invoice reporting',
    descriptionPl: 'Kompleksowe raporty faktur',
    icon: 'LineChart',
    category: 'ADDON',
    price: 69,
    isActive: true,
    isBeta: false,
    features: [
      'Raporty sprzedaży',
      'Analiza płatności',
      'Przeterminowane faktury',
      'Eksport raportów',
    ],
    routes: ['/invoices/reports'],
    apiEndpoints: ['/invoices/reports/*'],
    requiredSubmodules: ['INVOICES.SALES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 13,
  },
];

// ===========================================
// DEFINICJE PODMODUŁÓW - PROJECTS
// ===========================================

export const PROJECTS_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'PROJECTS.BASIC',
    parentModule: ModuleCode.PROJECTS,
    name: 'Basic Projects',
    namePl: 'Podstawowe projekty',
    description: 'Basic project management',
    descriptionPl: 'Podstawowe zarządzanie projektami',
    icon: 'FolderKanban',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Lista projektów',
      'Szczegóły projektu',
      'Status projektu',
      'Terminy',
    ],
    routes: ['/projects', '/projects/:id'],
    apiEndpoints: ['/projects/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'PROJECTS.TASKS',
    parentModule: ModuleCode.PROJECTS,
    name: 'Project Tasks',
    namePl: 'Zadania projektowe',
    description: 'Task management within projects',
    descriptionPl: 'Zarządzanie zadaniami w projektach',
    icon: 'CheckSquare',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Zadania projektowe',
      'Przypisanie wykonawców',
      'Statusy zadań',
      'Zależności zadań',
    ],
    routes: ['/projects/:id/tasks'],
    apiEndpoints: ['/projects/:id/tasks/*'],
    requiredSubmodules: ['PROJECTS.BASIC'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    code: 'PROJECTS.KANBAN',
    parentModule: ModuleCode.PROJECTS,
    name: 'Kanban Board',
    namePl: 'Tablica Kanban',
    description: 'Kanban-style task board',
    descriptionPl: 'Tablica zadań w stylu Kanban',
    icon: 'LayoutGrid',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Tablica Kanban',
      'Drag & drop',
      'Własne kolumny',
      'Limity WIP',
    ],
    routes: ['/projects/:id/kanban'],
    apiEndpoints: ['/projects/:id/kanban/*'],
    requiredSubmodules: ['PROJECTS.TASKS'],
    conflictsWith: ['PROJECTS.GANTT'],
    defaultEnabled: false,
    sortOrder: 3,
  },
  {
    code: 'PROJECTS.GANTT',
    parentModule: ModuleCode.PROJECTS,
    name: 'Gantt Chart',
    namePl: 'Wykres Gantta',
    description: 'Gantt chart timeline view',
    descriptionPl: 'Widok osi czasu (wykres Gantta)',
    icon: 'GanttChart',
    category: 'ADDON',
    price: 99,
    isActive: true,
    isBeta: false,
    features: [
      'Wykres Gantta',
      'Zależności zadań',
      'Kamienie milowe',
      'Ścieżka krytyczna',
    ],
    routes: ['/projects/:id/gantt'],
    apiEndpoints: ['/projects/:id/gantt/*'],
    requiredSubmodules: ['PROJECTS.TASKS'],
    conflictsWith: ['PROJECTS.KANBAN'],
    defaultEnabled: false,
    sortOrder: 4,
  },
  {
    code: 'PROJECTS.TIME',
    parentModule: ModuleCode.PROJECTS,
    name: 'Time Tracking',
    namePl: 'Śledzenie czasu',
    description: 'Time tracking for projects and tasks',
    descriptionPl: 'Śledzenie czasu pracy nad projektami',
    icon: 'Timer',
    category: 'ADDON',
    price: 89,
    isActive: true,
    isBeta: false,
    features: [
      'Śledzenie czasu',
      'Timer',
      'Raporty czasu pracy',
      'Rozliczanie godzinowe',
    ],
    routes: ['/projects/:id/time'],
    apiEndpoints: ['/projects/:id/time/*'],
    requiredSubmodules: ['PROJECTS.TASKS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 5,
  },
  {
    code: 'PROJECTS.BUDGET',
    parentModule: ModuleCode.PROJECTS,
    name: 'Budget Management',
    namePl: 'Zarządzanie budżetem',
    description: 'Project budget tracking',
    descriptionPl: 'Śledzenie budżetu projektów',
    icon: 'PiggyBank',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Budżet projektu',
      'Koszty rzeczywiste',
      'Analiza odchyleń',
      'Prognoza kosztów',
    ],
    routes: ['/projects/:id/budget'],
    apiEndpoints: ['/projects/:id/budget/*'],
    requiredSubmodules: ['PROJECTS.BASIC'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 6,
  },
  {
    code: 'PROJECTS.MILESTONES',
    parentModule: ModuleCode.PROJECTS,
    name: 'Milestones',
    namePl: 'Kamienie milowe',
    description: 'Project milestones and phases',
    descriptionPl: 'Kamienie milowe i fazy projektów',
    icon: 'Target',
    category: 'ADDON',
    price: 59,
    isActive: true,
    isBeta: false,
    features: [
      'Kamienie milowe',
      'Fazy projektu',
      'Progress tracking',
      'Deadline monitoring',
    ],
    routes: ['/projects/:id/milestones'],
    apiEndpoints: ['/projects/:id/milestones/*'],
    requiredSubmodules: ['PROJECTS.BASIC'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 7,
  },
  {
    code: 'PROJECTS.DOCS',
    parentModule: ModuleCode.PROJECTS,
    name: 'Project Documents',
    namePl: 'Dokumenty projektu',
    description: 'Centralized project documentation',
    descriptionPl: 'Scentralizowana dokumentacja projektu',
    icon: 'FileText',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Biblioteka dokumentów',
      'Wersjonowanie',
      'Udostępnianie',
      'Komentarze',
    ],
    routes: ['/projects/:id/docs'],
    apiEndpoints: ['/projects/:id/docs/*'],
    requiredSubmodules: ['PROJECTS.BASIC'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 8,
  },
  {
    code: 'PROJECTS.TEAM',
    parentModule: ModuleCode.PROJECTS,
    name: 'Team Management',
    namePl: 'Zarządzanie zespołem',
    description: 'Project team and roles',
    descriptionPl: 'Zespół projektowy i role',
    icon: 'Users',
    category: 'ADDON',
    price: 69,
    isActive: true,
    isBeta: false,
    features: [
      'Członkowie zespołu',
      'Role w projekcie',
      'Obciążenie zespołu',
      'Uprawnienia',
    ],
    routes: ['/projects/:id/team'],
    apiEndpoints: ['/projects/:id/team/*'],
    requiredSubmodules: ['PROJECTS.BASIC'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 9,
  },
  {
    code: 'PROJECTS.RISK',
    parentModule: ModuleCode.PROJECTS,
    name: 'Risk Management',
    namePl: 'Zarządzanie ryzykiem',
    description: 'Project risk identification and mitigation',
    descriptionPl: 'Identyfikacja i mitygacja ryzyka projektu',
    icon: 'AlertTriangle',
    category: 'ADDON',
    price: 89,
    isActive: true,
    isBeta: false,
    features: [
      'Rejestr ryzyk',
      'Ocena ryzyka',
      'Plan mitygacji',
      'Monitoring',
    ],
    routes: ['/projects/:id/risks'],
    apiEndpoints: ['/projects/:id/risks/*'],
    requiredSubmodules: ['PROJECTS.BASIC'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 10,
  },
  {
    code: 'PROJECTS.ISSUES',
    parentModule: ModuleCode.PROJECTS,
    name: 'Issue Tracking',
    namePl: 'Śledzenie problemów',
    description: 'Track and resolve project issues',
    descriptionPl: 'Śledzenie i rozwiązywanie problemów',
    icon: 'Bug',
    category: 'ADDON',
    price: 69,
    isActive: true,
    isBeta: false,
    features: [
      'Lista problemów',
      'Priorytety',
      'Przypisanie',
      'Resolution tracking',
    ],
    routes: ['/projects/:id/issues'],
    apiEndpoints: ['/projects/:id/issues/*'],
    requiredSubmodules: ['PROJECTS.BASIC'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 11,
  },
  {
    code: 'PROJECTS.REPORTS',
    parentModule: ModuleCode.PROJECTS,
    name: 'Project Reports',
    namePl: 'Raporty projektowe',
    description: 'Comprehensive project reporting',
    descriptionPl: 'Kompleksowe raporty projektowe',
    icon: 'BarChart',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Raporty postępu',
      'Analiza wykonania',
      'Burndown chart',
      'Eksport raportów',
    ],
    routes: ['/projects/:id/reports'],
    apiEndpoints: ['/projects/:id/reports/*'],
    requiredSubmodules: ['PROJECTS.BASIC', 'PROJECTS.TASKS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 12,
  },
  {
    code: 'PROJECTS.TEMPLATES',
    parentModule: ModuleCode.PROJECTS,
    name: 'Project Templates',
    namePl: 'Szablony projektów',
    description: 'Reusable project templates',
    descriptionPl: 'Szablony projektów do wielokrotnego użycia',
    icon: 'Copy',
    category: 'ADDON',
    price: 59,
    isActive: true,
    isBeta: false,
    features: [
      'Szablony projektów',
      'Predefiniowane zadania',
      'Szybkie uruchomienie',
      'Zarządzanie szablonami',
    ],
    routes: ['/settings/project-templates'],
    apiEndpoints: ['/projects/templates/*'],
    requiredSubmodules: ['PROJECTS.BASIC', 'PROJECTS.TASKS'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 13,
  },
];

// ===========================================
// DEFINICJE PODMODUŁÓW - REPORTS
// ===========================================

export const REPORTS_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'REPORTS.SALES',
    parentModule: ModuleCode.REPORTS,
    name: 'Sales Reports',
    namePl: 'Raporty sprzedaży',
    description: 'Comprehensive sales reporting',
    descriptionPl: 'Kompleksowe raporty sprzedaży',
    icon: 'TrendingUp',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Raport sprzedaży',
      'Analiza przychodów',
      'Porównania okresowe',
      'Wykresy',
    ],
    routes: ['/reports/sales'],
    apiEndpoints: ['/reports/sales/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'REPORTS.CUSTOMERS',
    parentModule: ModuleCode.REPORTS,
    name: 'Customer Reports',
    namePl: 'Raporty klientów',
    description: 'Customer analytics and insights',
    descriptionPl: 'Analityka i wgląd w klientów',
    icon: 'Users',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Nowi klienci',
      'Aktywni klienci',
      'Top klienci',
      'Segmentacja',
    ],
    routes: ['/reports/customers'],
    apiEndpoints: ['/reports/customers/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 2,
  },
  {
    code: 'REPORTS.FINANCIAL',
    parentModule: ModuleCode.REPORTS,
    name: 'Financial Reports',
    namePl: 'Raporty finansowe',
    description: 'Financial performance reports',
    descriptionPl: 'Raporty wydajności finansowej',
    icon: 'DollarSign',
    category: 'ADDON',
    price: 99,
    isActive: true,
    isBeta: false,
    features: [
      'Przychody i koszty',
      'Marża',
      'Rentowność',
      'Cash flow',
    ],
    routes: ['/reports/financial'],
    apiEndpoints: ['/reports/financial/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 3,
  },
  {
    code: 'REPORTS.INVENTORY',
    parentModule: ModuleCode.REPORTS,
    name: 'Inventory Reports',
    namePl: 'Raporty magazynowe',
    description: 'Stock and inventory reporting',
    descriptionPl: 'Raporty stanów magazynowych',
    icon: 'Package',
    category: 'ADDON',
    price: 79,
    isActive: true,
    isBeta: false,
    features: [
      'Stany magazynowe',
      'Rotacja towaru',
      'Wartość zapasów',
      'ABC analysis',
    ],
    routes: ['/reports/inventory'],
    apiEndpoints: ['/reports/inventory/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 4,
  },
  {
    code: 'REPORTS.EMPLOYEE',
    parentModule: ModuleCode.REPORTS,
    name: 'Employee Reports',
    namePl: 'Raporty pracowników',
    description: 'Employee performance and activity',
    descriptionPl: 'Wydajność i aktywność pracowników',
    icon: 'UserCheck',
    category: 'ADDON',
    price: 69,
    isActive: true,
    isBeta: false,
    features: [
      'Aktywność pracowników',
      'Zamówienia per pracownik',
      'Czas pracy',
      'Efektywność',
    ],
    routes: ['/reports/employees'],
    apiEndpoints: ['/reports/employees/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 5,
  },
  {
    code: 'REPORTS.CUSTOM',
    parentModule: ModuleCode.REPORTS,
    name: 'Custom Reports',
    namePl: 'Raporty własne',
    description: 'Build your own custom reports',
    descriptionPl: 'Twórz własne raporty',
    icon: 'Settings',
    category: 'ADDON',
    price: 149,
    isActive: true,
    isBeta: true,
    features: [
      'Kreator raportów',
      'Własne pola',
      'Filtry zaawansowane',
      'Zapisane raporty',
    ],
    routes: ['/reports/custom'],
    apiEndpoints: ['/reports/custom/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 6,
  },
  {
    code: 'REPORTS.EXPORT',
    parentModule: ModuleCode.REPORTS,
    name: 'Report Export',
    namePl: 'Eksport raportów',
    description: 'Export reports to various formats',
    descriptionPl: 'Eksport raportów do różnych formatów',
    icon: 'Download',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Export do Excel',
      'Export do PDF',
      'Export do CSV',
      'Automatyczny eksport',
    ],
    routes: [],
    apiEndpoints: ['/reports/export/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 7,
  },
  {
    code: 'REPORTS.SCHEDULED',
    parentModule: ModuleCode.REPORTS,
    name: 'Scheduled Reports',
    namePl: 'Raporty zaplanowane',
    description: 'Schedule automatic report generation',
    descriptionPl: 'Automatyczne generowanie raportów',
    icon: 'Clock',
    category: 'ADDON',
    price: 89,
    isActive: true,
    isBeta: false,
    features: [
      'Harmonogram raportów',
      'Email z raportem',
      'Cykliczne raporty',
      'Subskrypcje',
    ],
    routes: ['/reports/scheduled'],
    apiEndpoints: ['/reports/scheduled/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 8,
  },
  {
    code: 'REPORTS.DASHBOARD',
    parentModule: ModuleCode.REPORTS,
    name: 'Executive Dashboard',
    namePl: 'Dashboard zarządczy',
    description: 'Executive dashboard with KPIs',
    descriptionPl: 'Dashboard zarządczy z KPI',
    icon: 'LayoutDashboard',
    category: 'ADDON',
    price: 129,
    isActive: true,
    isBeta: false,
    features: [
      'KPI dashboard',
      'Wykresy real-time',
      'Widgets',
      'Personalizacja',
    ],
    routes: ['/reports/dashboard'],
    apiEndpoints: ['/reports/dashboard/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 9,
  },
  {
    code: 'REPORTS.COMPARISON',
    parentModule: ModuleCode.REPORTS,
    name: 'Comparison Reports',
    namePl: 'Raporty porównawcze',
    description: 'Compare periods and metrics',
    descriptionPl: 'Porównywanie okresów i metryk',
    icon: 'ArrowLeftRight',
    category: 'ADDON',
    price: 69,
    isActive: true,
    isBeta: false,
    features: [
      'Porównanie okresów',
      'YoY, MoM, WoW',
      'Benchmarking',
      'Wykresy porównawcze',
    ],
    routes: ['/reports/comparison'],
    apiEndpoints: ['/reports/comparison/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 10,
  },
  {
    code: 'REPORTS.FORECASTING',
    parentModule: ModuleCode.REPORTS,
    name: 'Forecasting',
    namePl: 'Prognozy',
    description: 'Sales and demand forecasting',
    descriptionPl: 'Prognozy sprzedaży i popytu',
    icon: 'TrendingUp',
    category: 'ADDON',
    price: 149,
    isActive: true,
    isBeta: true,
    features: [
      'Prognozowanie sprzedaży',
      'Analiza trendów',
      'Machine learning',
      'Planowanie zapasów',
    ],
    routes: ['/reports/forecasting'],
    apiEndpoints: ['/reports/forecasting/*'],
    requiredSubmodules: ['REPORTS.SALES'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 11,
  },
  {
    code: 'REPORTS.API',
    parentModule: ModuleCode.REPORTS,
    name: 'Reports API',
    namePl: 'API raportów',
    description: 'Programmatic access to reports',
    descriptionPl: 'Programowy dostęp do raportów',
    icon: 'Code',
    category: 'ADDON',
    price: 99,
    isActive: true,
    isBeta: false,
    features: [
      'REST API',
      'GraphQL',
      'Webhooks',
      'Integracje',
    ],
    routes: [],
    apiEndpoints: ['/reports/api/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 12,
  },
];

// ===========================================
// DEFINICJE PODMODUŁÓW - BRANCHES
// ===========================================

export const BRANCHES_SUBMODULES: SubmoduleDefinition[] = [
  {
    code: 'BRANCHES.BASIC',
    parentModule: ModuleCode.BRANCHES,
    name: 'Branch Management',
    namePl: 'Zarządzanie oddziałami',
    description: 'Multi-branch management',
    descriptionPl: 'Zarządzanie wielooddziałowe',
    icon: 'Building2',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Lista oddziałów',
      'Dane lokalizacji',
      'Kontakt',
      'Kierownik oddziału',
    ],
    routes: ['/settings/branches'],
    apiEndpoints: ['/branches/*'],
    requiredSubmodules: [],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 1,
  },
  {
    code: 'BRANCHES.POSTAL',
    parentModule: ModuleCode.BRANCHES,
    name: 'Postal Code Assignment',
    namePl: 'Auto-przypisanie po kodzie',
    description: 'Auto-assign orders by postal code',
    descriptionPl: 'Automatyczne przypisywanie zamówień po kodzie pocztowym',
    icon: 'MapPin',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Mapowanie kodów pocztowych',
      'Auto-przypisanie',
      'Prefiksy',
      'Fallback',
    ],
    routes: ['/settings/branches/postal'],
    apiEndpoints: ['/branches/postal/*'],
    requiredSubmodules: ['BRANCHES.BASIC'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 2,
  },
  {
    code: 'BRANCHES.USERS',
    parentModule: ModuleCode.BRANCHES,
    name: 'Branch Users',
    namePl: 'Pracownicy oddziałów',
    description: 'Assign users to branches',
    descriptionPl: 'Przypisanie pracowników do oddziałów',
    icon: 'Users',
    category: 'INCLUDED',
    price: null,
    isActive: true,
    isBeta: false,
    features: [
      'Przypisanie do oddziału',
      'Wielooddziałowi pracownicy',
      'Domyślny oddział',
      'Uprawnienia per oddział',
    ],
    routes: [],
    apiEndpoints: ['/branches/:id/users/*'],
    requiredSubmodules: ['BRANCHES.BASIC'],
    conflictsWith: [],
    defaultEnabled: true,
    sortOrder: 3,
  },
  {
    code: 'BRANCHES.REPORTS',
    parentModule: ModuleCode.BRANCHES,
    name: 'Branch Reports',
    namePl: 'Raporty per oddział',
    description: 'Branch performance reports',
    descriptionPl: 'Raporty wydajności oddziałów',
    icon: 'BarChart',
    category: 'ADDON',
    price: 49,
    isActive: true,
    isBeta: false,
    features: [
      'Statystyki oddziału',
      'Porównanie oddziałów',
      'Ranking',
      'Eksport',
    ],
    routes: ['/reports/branches'],
    apiEndpoints: ['/reports/branches/*'],
    requiredSubmodules: ['BRANCHES.BASIC'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 4,
  },
  {
    code: 'BRANCHES.TRANSFER',
    parentModule: ModuleCode.BRANCHES,
    name: 'Order Transfer',
    namePl: 'Transfer zleceń',
    description: 'Transfer orders between branches',
    descriptionPl: 'Przekazywanie zamówień między oddziałami',
    icon: 'ArrowRightLeft',
    category: 'ADDON',
    price: 29,
    isActive: true,
    isBeta: false,
    features: [
      'Transfer zamówień',
      'Historia transferów',
      'Powiadomienia',
      'Approval workflow',
    ],
    routes: [],
    apiEndpoints: ['/orders/:id/transfer'],
    requiredSubmodules: ['BRANCHES.BASIC'],
    conflictsWith: [],
    defaultEnabled: false,
    sortOrder: 5,
  },
];

// ===========================================
// WSZYSTKIE PODMODUŁY (AGREGACJA)
// ===========================================

export const ALL_SUBMODULES: SubmoduleDefinition[] = [
  ...CRM_SUBMODULES,
  ...ORDERS_SUBMODULES,
  ...PRODUCTS_SUBMODULES,
  ...QUOTES_SUBMODULES,
  ...WMS_SUBMODULES,
  ...CALENDAR_SUBMODULES,
  ...INVOICES_SUBMODULES,
  ...PROJECTS_SUBMODULES,
  ...REPORTS_SUBMODULES,
  ...BRANCHES_SUBMODULES,
];

// ===========================================
// SZABLONY BRANŻOWE
// ===========================================

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    code: 'SERVICES',
    name: 'Services',
    namePl: 'Usługi',
    description: 'Template for service businesses (installation, repair, etc.)',
    descriptionPl: 'Szablon dla firm usługowych (montaż, naprawa, itp.)',
    icon: 'Wrench',
    coreModules: [ModuleCode.CRM, ModuleCode.ORDERS],
    addonModules: [ModuleCode.QUOTES, ModuleCode.CALENDAR],
    defaultSubmodules: [
      'CRM.CONTACTS',
      'CRM.TAGS',
      'CRM.NOTES',
      'ORDERS.ITEMS',
      'ORDERS.WORKFLOW',
      'ORDERS.WORKFLOW_ADV',
      'ORDERS.MEASUREMENTS',
      'ORDERS.INSTALLATION',
      'ORDERS.ATTACHMENTS',
      'QUOTES.ITEMS',
      'QUOTES.PDF',
      'QUOTES.EMAIL',
      'CALENDAR.EVENTS',
      'CALENDAR.GOOGLE',
    ],
    hiddenSubmodules: ['WMS.*'],
  },
  {
    code: 'PRODUCTION',
    name: 'Production',
    namePl: 'Produkcja',
    description: 'Template for manufacturing businesses',
    descriptionPl: 'Szablon dla firm produkcyjnych',
    icon: 'Factory',
    coreModules: [ModuleCode.CRM, ModuleCode.ORDERS, ModuleCode.PRODUCTS],
    addonModules: [ModuleCode.WMS, ModuleCode.QUOTES],
    defaultSubmodules: [
      'CRM.CONTACTS',
      'CRM.TAGS',
      'ORDERS.ITEMS',
      'ORDERS.WORKFLOW',
      'ORDERS.WORKFLOW_ADV',
      'PRODUCTS.CATALOG',
      'PRODUCTS.CATEGORIES',
      'PRODUCTS.PRICELISTS',
      'PRODUCTS.DIMENSIONS',
      'PRODUCTS.SURCHARGES',
      'WMS.WAREHOUSES',
      'WMS.LOCATIONS',
      'WMS.STOCK',
      'WMS.DOCUMENTS',
      'WMS.INVENTORY',
      'QUOTES.ITEMS',
      'QUOTES.PDF',
      'QUOTES.CALCULATOR',
    ],
    hiddenSubmodules: ['ORDERS.MEASUREMENTS'],
  },
  {
    code: 'TRADE',
    name: 'Trade',
    namePl: 'Handel',
    description: 'Template for wholesale and distribution',
    descriptionPl: 'Szablon dla hurtowni i dystrybucji',
    icon: 'ShoppingCart',
    coreModules: [ModuleCode.CRM, ModuleCode.ORDERS, ModuleCode.PRODUCTS],
    addonModules: [ModuleCode.WMS, ModuleCode.INVOICES],
    defaultSubmodules: [
      'CRM.CONTACTS',
      'CRM.IMPORT',
      'CRM.SEGMENTS',
      'CRM.PORTAL',
      'ORDERS.ITEMS',
      'ORDERS.WORKFLOW',
      'PRODUCTS.CATALOG',
      'PRODUCTS.CATEGORIES',
      'PRODUCTS.IMPORT',
      'PRODUCTS.BARCODES',
      'PRODUCTS.PRICELISTS',
      'WMS.WAREHOUSES',
      'WMS.LOCATIONS',
      'WMS.STOCK',
      'WMS.CONTAINERS',
      'WMS.DOCUMENTS',
      'WMS.INVENTORY',
      'WMS.BARCODES',
      'WMS.ALERTS',
      'INVOICES.SALES',
      'INVOICES.PDF',
      'INVOICES.PAYMENTS',
    ],
    hiddenSubmodules: ['ORDERS.MEASUREMENTS'],
  },
];

// ===========================================
// HELPER FUNCTIONS
// ===========================================

/**
 * Get all submodules for a specific module
 */
export function getSubmodulesForModule(moduleCode: ModuleCode): SubmoduleDefinition[] {
  return ALL_SUBMODULES.filter((sub) => sub.parentModule === moduleCode);
}

/**
 * Get submodule by code
 */
export function getSubmoduleByCode(code: string): SubmoduleDefinition | undefined {
  return ALL_SUBMODULES.find((sub) => sub.code === code);
}

/**
 * Get template by code
 */
export function getTemplateByCode(
  code: 'SERVICES' | 'PRODUCTION' | 'TRADE',
): IndustryTemplate | undefined {
  return INDUSTRY_TEMPLATES.find((t) => t.code === code);
}

/**
 * Check if submodule dependencies are met
 */
export function checkSubmoduleDependencies(
  submoduleCode: string,
  enabledSubmodules: string[],
): { valid: boolean; missing: string[] } {
  const submodule = getSubmoduleByCode(submoduleCode);
  if (!submodule) {
    return { valid: false, missing: [] };
  }

  const missing = submodule.requiredSubmodules.filter(
    (req) => !enabledSubmodules.includes(req),
  );

  return {
    valid: missing.length === 0,
    missing,
  };
}

/**
 * Check if submodules conflict
 */
export function checkSubmoduleConflicts(
  submoduleCode: string,
  enabledSubmodules: string[],
): { hasConflict: boolean; conflicts: string[] } {
  const submodule = getSubmoduleByCode(submoduleCode);
  if (!submodule) {
    return { hasConflict: false, conflicts: [] };
  }

  const conflicts = submodule.conflictsWith.filter((conflict) =>
    enabledSubmodules.includes(conflict),
  );

  return {
    hasConflict: conflicts.length > 0,
    conflicts,
  };
}
